version: "3.3"

volumes:
  wireguard:
    driver: local

services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wireguard
    volumes:
      - /patch/to/data/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PASSWORD=${PASSWD}
      - WG_PORT=51820
      - WG_DEFAULT_DNS=1.1.1.1, 1.0.0.1
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - WG_HOST=YOUR_WANIP_OR_DOMAIN
    # Optional:
      # - WG_MTU=1420
      # - WG_DEFAULT_ADDRESS=10.8.0.x
    labels:
      # Watchtower Update 
      - "com.centurylinklabs.watchtower.enable=true"
