---
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:amd64-latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERPORT=51820
      - PEERS=PEER1, PEER2
      - PEERDNS=1.1.1.1, 1.0.0.1
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /home/jrodenas/docker/wireguard/appdata/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
